vagrant_version = "2"
box = 'precise32'
url = 'http://files.vagrantup.com/precise32.box'
hostname = 'vagrant'
domain = 'example.com'
ram = '256'

Vagrant.configure(vagrant_version) do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.vm.host_name = hostname + '.' + domain
  config.vm.synced_folder "../src/", "/var/www", create: true, group: "www-data", owner: "www-data"
  
  # config.berkshelf.enabled = true
  
  config.vm.provider :virtualbox do |v|
    v.name = "Go VM"
    v.customize [
        "modifyvm", :id, 
        '--name', hostname,
        "--memory", ram
    ] 
    v.gui = true
  end
end

$script = <<SCRIPT
apt-get update
mkdir -p /etc/puppet/modules
puppet module install garethr/golang
SCRIPT

Vagrant.configure(vagrant_version) do |config|
   config.vm.provision :shell, :inline => $script

#  config.vm.provision :shell do |s|
#    s.path "provision/setup.sh"
#  end
  
 config.vm.network :forwarded_port, guest: 27017, host: 27018
 
# config.vm.provision :chef_solo do |chef|
#   chef.cookbooks_path = ['chef/cookbooks']
#   chef.recipe_url = 'https://github.com/opscode-cookbooks/zsh/master'
#   chef.add_recipe "zsh"
#   # chef.add_recipe "mongodb::10gen_repo"
#   # chef.add_recipe "vim"
#   # chef.add_recipe "curl"
#   # chef.add_recipe "apt"
#   # chef.add_recipe "build-essential"
# end
 config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'site.pp'
    puppet.module_path = 'puppet/modules'
 end

end