Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.host_name = 'vagrant'
  config.vm.synced_folder "../", "/var/www", create: true, group: "www-data", owner: "www-data"
  
  config.vm.provider :virtualbox do |v|
    v.name = "Go VM"
    v.customize ["modifyvm", :id, "--memory", "512"]  
  end
end

$script = <<SCRIPT
apt-get update
SCRIPT

Vagrant.configure("2") do |config|
   config.vm.provision :shell, :inline => $script

#  config.vm.provision :shell do |s|
#    s.path "provision/setup.sh"
#  end
  
 config.vm.network :forwarded_port, guest: 27017, host: 27018
 
 config.vm.provision :chef_solo do |chef|
   chef.cookbooks_path = ['chef/cookbooks']
   chef.recipe_url = 'https://github.com/opscode-cookbooks/zsh/master'
   chef.add_recipe "zsh"
#   # chef.add_recipe "mongodb::10gen_repo"
#   # chef.add_recipe "vim"
#   # chef.add_recipe "curl"
#   # chef.add_recipe "apt"
#   # chef.add_recipe "build-essential"
 end

end